# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chatbot.proto',
  package='chatbot',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rchatbot.proto\x12\x07\x63hatbot\"!\n\x0e\x43hatBotRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0f\x43hatBotResponse\x12\x10\n\x08response\x18\x01 \x01(\t2S\n\x0e\x43hatbotService\x12\x41\n\nGetMessage\x12\x17.chatbot.ChatBotRequest\x1a\x18.chatbot.ChatBotResponse\"\x00\x62\x06proto3')
)




_CHATBOTREQUEST = _descriptor.Descriptor(
  name='ChatBotRequest',
  full_name='chatbot.ChatBotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='chatbot.ChatBotRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=59,
)


_CHATBOTRESPONSE = _descriptor.Descriptor(
  name='ChatBotResponse',
  full_name='chatbot.ChatBotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='chatbot.ChatBotResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['ChatBotRequest'] = _CHATBOTREQUEST
DESCRIPTOR.message_types_by_name['ChatBotResponse'] = _CHATBOTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatBotRequest = _reflection.GeneratedProtocolMessageType('ChatBotRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHATBOTREQUEST,
  __module__ = 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatbot.ChatBotRequest)
  ))
_sym_db.RegisterMessage(ChatBotRequest)

ChatBotResponse = _reflection.GeneratedProtocolMessageType('ChatBotResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHATBOTRESPONSE,
  __module__ = 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatbot.ChatBotResponse)
  ))
_sym_db.RegisterMessage(ChatBotResponse)



_CHATBOTSERVICE = _descriptor.ServiceDescriptor(
  name='ChatbotService',
  full_name='chatbot.ChatbotService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=98,
  serialized_end=181,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMessage',
    full_name='chatbot.ChatbotService.GetMessage',
    index=0,
    containing_service=None,
    input_type=_CHATBOTREQUEST,
    output_type=_CHATBOTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATBOTSERVICE)

DESCRIPTOR.services_by_name['ChatbotService'] = _CHATBOTSERVICE

# @@protoc_insertion_point(module_scope)
