# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chatbot_pb2 as chatbot__pb2


class ChatbotServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMessage = channel.unary_unary(
        '/chatbot.ChatbotService/GetMessage',
        request_serializer=chatbot__pb2.ChatBotRequest.SerializeToString,
        response_deserializer=chatbot__pb2.ChatBotResponse.FromString,
        )


class ChatbotServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatbotServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMessage': grpc.unary_unary_rpc_method_handler(
          servicer.GetMessage,
          request_deserializer=chatbot__pb2.ChatBotRequest.FromString,
          response_serializer=chatbot__pb2.ChatBotResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chatbot.ChatbotService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
